name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - run: mkdir -p release
    - run: mv target/release/space-colonization* release/
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/space-colonization*
